df1 <- data.frame(SiteId=c(1:6),Site=c("Google","Runoob","Taobao","Facebook","Zhihu","Weibo"))
df2 <- data.frame(SiteId = c(2, 4, 6, 7, 8), Country = c("CN","USA","CN","USA","IN"))
df1 <- merge(x=df1,y=df2,by="SiteId")
print("----- INNER JOIN -----")
print(df1)

df2 <- merge(x=df1,y=df2,by="SiteId",all=TRUE)
print("----- FULL JOIN -----")
print(df2)

df3 <- merge(x=df1,y=df2,by="SiteId",all.x=TRUE)
print("----- LEFT Join -----")
print(df3)

df4 <- merge(x=df1,y=df2,by="SiteId",all.y=TRUE)
print("----- LEFT Join -----")
print(df4)

library(MASS)
library(reshape2)
library(reshape)
id <- c(1,1,2,2)
time <- c(1,2,1,2)
x1 <- c(5,3,6,2)
x2 <- c(6,5,1,4)
mydata <- data.frame(id,time,x1,x2)
cat("原始数据框：","\n")
print(mydata)
md <- melt(mydata,id=c("id","time"))
cat("\n整合后数据框：\n")
print(md)

# 创建数据框
id<- c(1, 1, 2, 2)
time <- c(1, 2, 1, 2)
x1 <- c(5, 3, 6, 2)
x2 <- c(6, 5, 1, 4)
mydata <- data.frame(id, time, x1, x2)
# 整合
md <- melt(mydata,id=c("id","time"))
cast.data <- cast(md,id~variable,mean)
print(cast.data)
cat("\n")
time.cast <- cast(md,id~variable,mean)
print(time.cast)
cat("\n")
id.time <- cast(md, id~time, mean)
print(id.time)

cat("\n")
id.time.cast <- cast(md, id+time~variable)
print(id.time.cast)

cat("\n")
id.variable.time <- cast(md, id+variable~time)
print(id.variable.time)

cat("\n")
id.variable.time2 <- cast(md, id~variable+time)
print(id.variable.time2)
